import type { ChatMock, ChatSidebarAppealItem } from "./Chat.types";

const AVATAR_DOMOVOY = "/favicon.svg";
const AVATAR_ELENA = "https://i.pravatar.cc/60?u=elena-sokolova";
const AVATAR_ANNA = "https://i.pravatar.cc/60?u=anna-k";
const AVATAR_IGOR = "https://i.pravatar.cc/60?u=igor-m";
const AVATAR_MARIA = "https://i.pravatar.cc/60?u=maria-s";

/** Мок чата заявки */
export const APPEAL_CHAT_MOCK: ChatMock = {
	id: "appeal-1842",
	type: "appeal",
	headerType: "appeal",
	title: "Протечка",
	subtitle: "В работе",
	status: "in-progress",
	badgeCount: 1,
	sidebarMeta: "В работе · 12:24",
	number: "1842",
	operator: {
		name: "Елена Соколова",
		role: "Диспетчер УК «Городская»",
		initials: "ЕС",
		avatarUrl: AVATAR_ELENA,
	},
	messages: [
		{
			id: "1",
			kind: "out",
			dateLabel: "20 сентября",
			text: "На восьмом этаже течёт вода с потолка возле лифта.",
			time: "18:42",
			delivery: "read",
		},
		{
			id: "2",
			kind: "bot",
			author: "Домовой",
			avatarUrl: AVATAR_DOMOVOY,
			dateLabel: "20 сентября",
			text: "Понял. Определяю ответственную организацию и регистрирую обращение.",
			time: "18:42",
		},
		{
			id: "3",
			kind: "bot",
			author: "Домовой",
			avatarUrl: AVATAR_DOMOVOY,
			dateLabel: "20 сентября",
			text: "Обращение № 1842 направлено в УК «Городская». Нормативный срок реакции на аварийную заявку — 30 минут.",
			time: "18:43",
		},
		{
			id: "4",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "20 сентября",
			text: "Заявку приняла. Аварийная бригада уже выехала, ориентировочное прибытие — до 19:15.",
			time: "18:51",
		},
		{
			id: "5",
			kind: "out",
			dateLabel: "20 сентября",
			text: "Спасибо. Вода уже капает сильнее, можно ли ускорить?",
			time: "18:55",
			delivery: "read",
		},
		{
			id: "6",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "20 сентября",
			text: "Передала диспетчеру. Бригада на объекте через 10–15 минут.",
			time: "18:58",
		},
		{
			id: "7",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "20 сентября",
			text: "Мы на месте. Перекрыли стояк на ночь, завтра продолжим работы на перекрытии.",
			time: "19:40",
		},
		{
			id: "8",
			kind: "bot",
			author: "Домовой",
			avatarUrl: AVATAR_DOMOVOY,
			dateLabel: "Вчера",
			text: "Статус обращения обновлён: работы продолжаются.",
			time: "09:10",
		},
		{
			id: "9",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "Вчера",
			text: "Доброе утро. Возобновили работы, устраняем протечку на межэтажном перекрытии.",
			time: "09:22",
		},
		{
			id: "10",
			kind: "out",
			dateLabel: "Вчера",
			text: "Ок. Нужен ли доступ в квартиру?",
			time: "09:28",
			delivery: "read",
		},
		{
			id: "11",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "Вчера",
			text: "Пока нет, работаем в шахте лифта и на площадке. Если понадобится — напишем.",
			time: "09:31",
		},
		{
			id: "12",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "Вчера",
			text: "Основную течь закрыли. Оставляем наблюдение до завтра, затем откроем стояк полностью.",
			time: "16:05",
		},
		{
			id: "13",
			kind: "bot",
			author: "Домовой",
			avatarUrl: AVATAR_DOMOVOY,
			dateLabel: "Сегодня",
			text: "Напоминание: после устранения можно запросить акт выполненных работ в этом чате.",
			time: "10:12",
		},
		{
			id: "14",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "Сегодня",
			text: "Протечку устранили, стояк открыли. Проверьте, пожалуйста, что капель больше нет.",
			time: "11:48",
		},
		{
			id: "15",
			kind: "out",
			dateLabel: "Сегодня",
			text: "Проверил — вроде сухо. Можно закрывать заявку?",
			time: "12:03",
			delivery: "read",
		},
		{
			id: "16",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "Сегодня",
			text: "Да, если всё в порядке — подтвердите, и мы подготовим акт.",
			time: "12:07",
		},
	],
};

/** Мок чата заявки — свет */
export const LIGHT_APPEAL_CHAT_MOCK: ChatMock = {
	id: "appeal-light",
	type: "appeal",
	headerType: "appeal",
	title: "Не горит свет на этаже",
	subtitle: "Ждёт подтверждения",
	status: "executed",
	sidebarMeta: "Ждёт подтверждения",
	number: "1901",
	operator: {
		name: "Елена Соколова",
		role: "Диспетчер УК «Городская»",
		initials: "ЕС",
		avatarUrl: AVATAR_ELENA,
	},
	messages: [
		{
			id: "1",
			kind: "out",
			dateLabel: "18 сентября",
			text: "На 5 этаже не горит свет в коридоре уже два дня.",
			time: "14:10",
			delivery: "read",
		},
		{
			id: "2",
			kind: "bot",
			author: "Домовой",
			avatarUrl: AVATAR_DOMOVOY,
			dateLabel: "18 сентября",
			text: "Обращение № 1901 принято. Электрик выезжает сегодня.",
			time: "14:12",
		},
		{
			id: "3",
			kind: "operator",
			author: "Елена Соколова",
			avatarUrl: AVATAR_ELENA,
			dateLabel: "18 сентября",
			text: "Лампу заменили. Подтвердите, пожалуйста, что свет горит.",
			time: "17:40",
		},
	],
};

/** Мок чата заявки — вода */
export const WATER_APPEAL_CHAT_MOCK: ChatMock = {
	id: "appeal-water",
	type: "appeal",
	headerType: "appeal",
	title: "Перебои с горячей водой",
	subtitle: "Закрыто",
	status: "closed",
	sidebarMeta: "Закрыто · 12 сент.",
	number: "1755",
	operator: {
		name: "Елена Соколова",
		role: "Диспетчер УК «Городская»",
		initials: "ЕС",
		avatarUrl: AVATAR_ELENA,
	},
	messages: [
		{
			id: "1",
			kind: "out",
			dateLabel: "12 сентября",
			text: "С утра нет горячей воды во всём стояке.",
			time: "09:05",
			delivery: "read",
		},
		{
			id: "2",
			kind: "bot",
			author: "Домовой",
			avatarUrl: AVATAR_DOMOVOY,
			dateLabel: "12 сентября",
			text: "Заявка закрыта: подача восстановлена.",
			time: "18:20",
		},
	],
};

/** Мок чата жителей */
export const CONVERSATION_CHAT_MOCK: ChatMock = {
	id: "residents",
	type: "conversation",
	headerType: "conversation",
	title: "Чат жителей дома",
	subtitle: "128 участников",
	badgeCount: 1,
	messages: [
		{
			id: "1",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "19 сентября",
			text: "Добрый вечер! Кто-нибудь оставлял заявку по домофону?",
			time: "20:14",
		},
		{
			id: "2",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "19 сентября",
			text: "У нас во 2 подъезде уже неделю не открывается с улицы.",
			time: "20:15",
		},
		{
			id: "3",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "19 сентября",
			text: "Может, кто-то знает контакты мастера?",
			time: "20:15",
		},
		{
			id: "4",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "19 сентября",
			text: "Я писал в УК утром, сказали, что мастер приедет завтра.",
			time: "20:18",
		},
		{
			id: "5",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "19 сентября",
			text: "Оставил заявку № 1204, обещали до 15:00.",
			time: "20:19",
		},
		{
			id: "6",
			kind: "out",
			dateLabel: "19 сентября",
			text: "У нас тоже не открывается с улицы.",
			time: "20:21",
			delivery: "read",
		},
		{
			id: "7",
			kind: "out",
			dateLabel: "19 сентября",
			text: "Если что — могу подойти к мастеру, когда приедет.",
			time: "20:22",
			delivery: "read",
		},
		{
			id: "8",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "19 сентября",
			text: "У нас в 3 подъезде пока работает, стучите если что.",
			time: "20:30",
		},
		{
			id: "9",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "Вчера",
			text: "Кто-нибудь знает, когда включат горячую воду?",
			time: "10:12",
		},
		{
			id: "10",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "Вчера",
			text: "Уже второй день без неё, дети дома.",
			time: "10:13",
		},
		{
			id: "11",
			kind: "out",
			dateLabel: "Вчера",
			text: "В нашем подъезде тоже нет с утра.",
			time: "10:15",
			delivery: "read",
		},
		{
			id: "12",
			kind: "out",
			dateLabel: "Вчера",
			text: "На доске УК висит объявление — плановые работы.",
			time: "10:16",
			delivery: "read",
		},
		{
			id: "13",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "Вчера",
			text: "УК написала, что работы до вечера.",
			time: "10:22",
		},
		{
			id: "14",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "Вчера",
			text: "Ориентир — до 18:00, потом должны дать.",
			time: "10:23",
		},
		{
			id: "15",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "Вчера",
			text: "По домофону мастер был, ключ перепрограммировали. Проверьте вечером.",
			time: "16:40",
		},
		{
			id: "16",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "Вчера",
			text: "Домофон снова открывается, спасибо!",
			time: "19:05",
		},
		{
			id: "17",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "Вчера",
			text: "А вода так и не появилась",
			time: "19:06",
		},
		{
			id: "18",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "Вчера",
			text: "У нас в 3 тоже пока холодная.",
			time: "19:12",
		},
		{
			id: "19",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "Вчера",
			text: "Напишу диспетчеру ещё раз.",
			time: "19:13",
		},
		{
			id: "20",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "Сегодня",
			text: "Горячая вода появилась около 8 утра, у всех так?",
			time: "08:41",
		},
		{
			id: "21",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "Сегодня",
			text: "Давление нормальное, температура тоже ок.",
			time: "08:42",
		},
		{
			id: "22",
			kind: "out",
			dateLabel: "Сегодня",
			text: "Да, у нас тоже уже есть.",
			time: "08:46",
			delivery: "read",
		},
		{
			id: "23",
			kind: "out",
			dateLabel: "Сегодня",
			text: "Наконец-то",
			time: "08:46",
			delivery: "read",
		},
		{
			id: "24",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "Сегодня",
			text: "У нас тоже появилась, спасибо всем за апдейты.",
			time: "08:55",
		},
		{
			id: "25",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "Сегодня",
			text: "Отлично. По домофону всё стабильно?",
			time: "09:05",
		},
		{
			id: "26",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "Сегодня",
			text: "Если снова отвалится — пишите, заявку продублирую.",
			time: "09:06",
		},
		{
			id: "27",
			kind: "bot",
			author: "Анна К.",
			avatarUrl: AVATAR_ANNA,
			dateLabel: "Сегодня",
			text: "Пока держится, утром открывала нормально.",
			time: "09:10",
		},
		{
			id: "28",
			kind: "out",
			dateLabel: "Сегодня",
			text: "У нас тоже ок.",
			time: "09:12",
			delivery: "read",
		},
		{
			id: "29",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "Сегодня",
			text: "Кто идёт на субботник в эту субботу?",
			time: "10:20",
		},
		{
			id: "30",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "Сегодня",
			text: "УК просила помочь с клумбами у 1 подъезда.",
			time: "10:21",
		},
		{
			id: "31",
			kind: "bot",
			author: "Мария С.",
			avatarUrl: AVATAR_MARIA,
			dateLabel: "Сегодня",
			text: "Сбор в 10:00 у лавочек.",
			time: "10:21",
		},
		{
			id: "32",
			kind: "operator",
			author: "Игорь М.",
			avatarUrl: AVATAR_IGOR,
			dateLabel: "Сегодня",
			text: "Я подойду, возьму лопату.",
			time: "10:28",
		},
		{
			id: "33",
			kind: "out",
			dateLabel: "Сегодня",
			text: "Я тоже буду.",
			time: "10:31",
			delivery: "delivered",
		},
		{
			id: "34",
			kind: "out",
			dateLabel: "Сегодня",
			text: "Могу принести перчатки, если кому надо.",
			time: "10:32",
			delivery: "sent",
		},
	],
};

/** Чаты по id */
export const CHAT_MOCKS: Record<string, ChatMock> = {
	[APPEAL_CHAT_MOCK.id]: APPEAL_CHAT_MOCK,
	[LIGHT_APPEAL_CHAT_MOCK.id]: LIGHT_APPEAL_CHAT_MOCK,
	[WATER_APPEAL_CHAT_MOCK.id]: WATER_APPEAL_CHAT_MOCK,
	[CONVERSATION_CHAT_MOCK.id]: CONVERSATION_CHAT_MOCK,
};

/** Обращения в сайдбаре */
export const CHAT_SIDEBAR_APPEALS: ChatSidebarAppealItem[] = [
	APPEAL_CHAT_MOCK,
	LIGHT_APPEAL_CHAT_MOCK,
	WATER_APPEAL_CHAT_MOCK,
].map((chat) => ({
	id: chat.id,
	title: chat.id === APPEAL_CHAT_MOCK.id ? "Протечка в подъезде" : chat.title,
	meta: chat.sidebarMeta ?? chat.subtitle,
	status: chat.status ?? "in-progress",
}));

/** Чат по умолчанию */
export const DEFAULT_CHAT_ID = CONVERSATION_CHAT_MOCK.id;

/** Подпись дня для новых сообщений */
export const CHAT_TODAY_LABEL = "Сегодня";
