[project]
name = "umniy-dom-max"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "loguru>=0.7.3",
    "pydantic-ai-slim[openai]>=2.46.0",
    "pydantic-settings",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy[asyncio]>=2.0.54",
    "urllib3>=2.8.0",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
api = "umniy_dom_max.cmd.api:main"
bot = "umniy_dom_max.cmd.bot:main"
clear-db = "umniy_dom_max.cmd.clear_db:main"

[tool.uv]
package = true
